/*
 * This file is generated by jOOQ.
 */
package revolut.backendtest.persistence.jooq.codegen;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import revolut.backendtest.persistence.jooq.codegen.tables.Accounts;
import revolut.backendtest.persistence.jooq.codegen.tables.Transfers;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;
    public static final Index CONSTRAINT_INDEX_E = Indexes0.CONSTRAINT_INDEX_E;
    public static final Index CONSTRAINT_INDEX_E4 = Indexes0.CONSTRAINT_INDEX_E4;
    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.ACCOUNT_ID }, true);
        public static Index CONSTRAINT_INDEX_E = Internal.createIndex("CONSTRAINT_INDEX_E", Transfers.TRANSFERS, new OrderField[] { Transfers.TRANSFERS.FROM_ACCOUNT_ID }, false);
        public static Index CONSTRAINT_INDEX_E4 = Internal.createIndex("CONSTRAINT_INDEX_E4", Transfers.TRANSFERS, new OrderField[] { Transfers.TRANSFERS.TO_ACCOUNT_ID }, false);
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", Transfers.TRANSFERS, new OrderField[] { Transfers.TRANSFERS.TRANSFER_ID }, true);
    }
}
