/*
 * This file is generated by jOOQ.
 */
package revolut.backendtest.persistence.jooq.codegen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import revolut.backendtest.persistence.jooq.codegen.tables.Accounts;
import revolut.backendtest.persistence.jooq.codegen.tables.Transfers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1477730528;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNTS</code>.
     */
    public final Accounts ACCOUNTS = revolut.backendtest.persistence.jooq.codegen.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>PUBLIC.TRANSFERS</code>.
     */
    public final Transfers TRANSFERS = revolut.backendtest.persistence.jooq.codegen.tables.Transfers.TRANSFERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accounts.ACCOUNTS,
            Transfers.TRANSFERS);
    }
}
