/*
 * This file is generated by jOOQ.
 */
package revolut.backendtest.persistence.jooq.codegen;


import javax.annotation.Generated;

import revolut.backendtest.persistence.jooq.codegen.tables.Accounts;
import revolut.backendtest.persistence.jooq.codegen.tables.Transfers;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNTS</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>PUBLIC.TRANSFERS</code>.
     */
    public static final Transfers TRANSFERS = Transfers.TRANSFERS;
}
